---
# handlers file for apache
- name: "Restart Apache"
  become: yes
  become_method: sudo
  systemd:
   name: apache2
   daemon_reload: yes
   state: restarted
  tags: httpd

- name: "Reload Apache"
  become: yes
  become_method: sudo
  systemd:
   name: apache2
   daemon_reload: yes
   state: reloaded
  tags: httpd
