---
# tasks for configure

- name: "Be sure to have needed directories on the volume"
  file:
   path: "{{ item }}"
   state: directory
   mode: 0755
  with_items:
   - "{{ common['volumes'][0]['volume_path'] }}/var"
   - "{{ common['volumes'][0]['volume_path'] }}/var/log"
  when:
   - common is defined
   - common['volumes'][0]['volume_path'] is defined
   - common['volumes'][0]['volume_path'] != ""

- name: "Be sure to configure correctly Rsyslog server"
  template:
   src: "conf/relp.conf.j2"
   dest: "/etc/rsyslog.d/22-relp.conf"
   owner: "root"
   group: "root"
   mode: 0644
  notify:
   - "Restart Rsyslog"
  when:
   - common is defined
   - common['volumes'][0]['volume_path'] is defined
   - common['volumes'][0]['volume_path'] != ""

- name: "Be sure to manage logs' backups"
  template:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   owner: "root"
   group: "root"
   mode: 0755
  with_items:
   - { src: "conf/gzip-remote-logs.j2" , dest: "/etc/cron.daily/gzip-remote-logs"}
   - { src: "conf/remove-old-logs.j2" , dest: "/etc/cron.monthly/remove-old-logs"}
