---
# tasks for configure.yml

# tasks file for IdP Style and Languages
- name: "Check if Apache Kibana conf is already enabled"
  stat:
   path: "/etc/apache2/conf-enabled/kibana.conf"
  register: kibana_apache
  changed_when: false

- name: "Add Apache Kibana conf"
  template:
   src: "kibana.conf.j2"
   dest: "/etc/apache2/conf-available/kibana.conf"
   owner: "root"
   group: "root"
   mode: "0600"
  when: kibana_apache.stat.islnk is not defined
  notify:
   - "Restart Apache"

- name: "Add Kibana support to Apache HTTPS VirtualHost"
  blockinfile:
    path: "/etc/apache2/sites-available/{{ fqdn }}-ssl.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - KIBANA"
    insertbefore: "</VirtualHost>"
    block: |
      Include conf-available/kibana.conf
  when: kibana_apache.stat.islnk is not defined
  notify:
   - "Restart Apache"

- name: "Be sure to configure correctly kibana"
  template:
   src: "conf/kibana.yml.j2"
   dest: "/etc/kibana/kibana.yml"
   owner: "root"
   group: "root"
   mode: "0644"
   backup: "yes"
  notify:
   - "Restart Kibana"

- name: "Be sure to enable kibana service and ensure it is not masked"
  systemd:
   name: "kibana.service"
   daemon_reload: yes
   enabled: yes
   state: started
   masked: no
