---
# tasks file for kibana
- name: "Be sure that kibana GPG Key is installed"
  apt_key:
    id: "D88E42B4"
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: "Be sure to add elastic repository"
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present
    filename: 'elastic-7.x'

- name: "Be sure to install the kibana package"
  apt:
   name: "kibana"
   state: latest
   update_cache: yes

- name: "Be sure to have created needed directory on the existent volume"
  file:
   path: "{{ item }}" 
   state: directory
   mode: 0755
  with_items:
   - "{{ common['volumes'][0]['volume_path'] }}/log"
   - "{{ common['volumes'][0]['volume_path'] }}/log/kibana"
  when:
   - common is defined
   - common['volumes'] is defined
   - common['volumes'][0]['volume_path'] is defined
   - common['volumes'][0]['volume_path'] != ""
