---
# handlers file for common
- name: "Restart ntp"
  systemd: 
   name: ntp
   daemon-reload: yes
   state: restarted

- name: "Restart SSH"
  systemd:
   name: ssh
   daemon-reload: yes
   state: restarted

- name: "Update Timezone"
  shell: dpkg-reconfigure --frontend noninteractive tzdata  
