---
# tasks for configure.yml
- name: "Be sure to have created needed directory for elastichsearch custom configurations"
  file:
   path: "/etc/systemd/system/elasticsearch.service.d"
   state: directory
   mode: 0755
   owner: "elasticsearch"
   group: "elasticsearch"

- name: "Apply elasticsearch custom configurations"
  template:
   src: "conf/override.conf.j2"
   dest: "/etc/systemd/system/elasticsearch.service.d/override.conf"
   owner: "root"
   group: "elasticsearch"
  notify:
   - "Restart Elasticsearch"

- name: "Be sure to configure elasticsearch default"
  replace:
   dest: "/etc/default/elasticsearch"
   regexp: "{{ item['regexp'] }}"
   replace: "{{ item['replace'] }}"
  with_items:
   - { regexp: "#JAVA_HOME=", replace: "JAVA_HOME=/usr/lib/jvm/default-java" }
   - { regexp: "#MAX_LOCKED_MEMORY=unlimited", replace: "MAX_LOCKED_MEMORY=unlimited" }

- name: "Be sure to have created needed directory on the existent volume"
  file:
   path: "{{ item }}" 
   state: directory
   mode: 0755
   owner: "elasticsearch"
   group: "elasticsearch"
  with_items:
   - "{{ common['volumes'][0]['volume_path'] }}/log"
   - "{{ common['volumes'][0]['volume_path'] }}/log/elasticsearch"
   - "{{ common['volumes'][0]['volume_path'] }}/elasticsearch-data"
  when:
   - common is defined
   - common['volumes'][0]['volume_path'] is defined
   - common['volumes'][0]['volume_path'] != ""

- name: "Be sure to configure correctly elasticsearch"
  template:
   src: "conf/elasticsearch.yml.j2"
   dest: "/etc/elasticsearch/elasticsearch.yml"
   owner: "root"
   group: "elasticsearch"
   mode: "0660"
   backup: "yes"
  notify:
   - "Restart Elasticsearch"

- name: "Be sure to enable elasticsearch service and ensure it is not masked"
  systemd:
   name: "elasticsearch.service"
   daemon_reload: yes
   enabled: yes
   state: started
   masked: no
  changed_when: false
