---
# tasks file for jdk

- name: "Install Amazon Corretto JDK"
  import_tasks: "install_corretto_Debian.yml"
  when: jdk_type == "corretto" and ansible_os_family == 'Debian'
  tags: jdk

- name: "Install OpenJDK"
  import_tasks: "install_openjdk_Debian.yml"
  when: jdk_type == "openjdk" and ansible_os_family == 'Debian'
  tags: jdk

- name: "Install Oracle JDK"
  import_tasks: "install_oraclejdk_Debian.yml"
  when: jdk_type == "oraclejdk" and ansible_os_family == 'Debian'
  tags: jdk
