---
# task for install.yml
- name: "Run 'apt-get update' if the last one is more than 3600 seconds ago"
  apt:
   update_cache: yes
   cache_valid_time: 3600
  tags: common

- name: "Install gdebi package manager" 
  apt: 
   pkg: "gdebi-core"
   state: latest
   install_recommends: no

- name: "Install passlib needed for htpasswd ansible module" 
  apt: 
   pkg: "python3-passlib"
   state: latest
   install_recommends: no

- name: "Be sure to load Check MK package to install"
  copy:
   src: "{{ files_dir }}/{{ fqdn }}/{{ ansible_distribution }}/{{ ansible_distribution_release }}/"
   dest: "/usr/local/src/"
   owner: "root"
   group: "root"
   mode: "0644"

- name: "Retrieve Check MK deb name"
  shell: "ls | tail -n 1 | grep check-mk-raw"
  args:
    chdir: /usr/local/src
  changed_when: false
  register: check_mk_deb
  tags: checkmk_upd

- name: "Be sure to install '{{ check_mk_deb['stdout'] }}'"
  command: "gdebi {{ check_mk_deb['stdout'] }} -n"
  args:
    chdir: /usr/local/src
    creates: /opt/omd
